#import <Foundation/Foundation.h>

FOUNDATION_EXTERN NSString  *CONTROL_SERVICE_UUID;
FOUNDATION_EXTERN NSString  *WRITE_SERVICE_UUID;
FOUNDATION_EXTERN NSString  *NOTIFICATION_SERVICE_UUID;

FOUNDATION_EXTERN Byte LOCK_UP[];
FOUNDATION_EXTERN Byte LOCK_UP_FORCED[];
FOUNDATION_EXTERN Byte LOCK_DOWN[];
FOUNDATION_EXTERN Byte LOCK_RESET[];
FOUNDATION_EXTERN Byte PASSWORD_VERIFITY_SUCCESS_STATE[];
FOUNDATION_EXTERN Byte PASSWORD_VERIFITY_FAIL_STATE[];
FOUNDATION_EXTERN NSString *LOCK_STATUS_IS_UP;
FOUNDATION_EXTERN NSString *LOCK_STATUS_IS_DOWN;
FOUNDATION_EXTERN NSString *LOCK_STATUS_IS_EXCEPTION;
FOUNDATION_EXTERN NSString *LOCK_STATUS_NO_CAR;
FOUNDATION_EXTERN NSString *LOCK_STATUS_HAS_CAR;
FOUNDATION_EXTERN NSString *LOCK_STATUS_UP;
FOUNDATION_EXTERN NSString *LOCK_STATUS_DOWN;
FOUNDATION_EXTERN NSString *LOCK_STATUS_BARRIER;
FOUNDATION_EXTERN Byte LOCK_SEARCH_KEEP[];
FOUNDATION_EXTERN Byte LOCK_SEARCH_LEAVE[];
FOUNDATION_EXTERN NSString *phone;
FOUNDATION_EXTERN NSString *password;
FOUNDATION_EXTERN NSString *secretKey;
FOUNDATION_EXTERN NSString *shareSuccess;
FOUNDATION_EXTERN NSString *unbindLock;
FOUNDATION_EXTERN NSString *bluetoothConnect;
FOUNDATION_EXTERN NSString *bluetoothAddLock;
FOUNDATION_EXTERN NSString *userCancelShare;
FOUNDATION_EXTERN NSString *loginOut;
FOUNDATION_EXTERN NSString *updateUserInfo;
FOUNDATION_EXTERN NSString *remoteNotification;
FOUNDATION_EXTERN NSString *userAvaterContentUrl;
